name: serhii-goodbye-html

services:
    app:
        build:
            context: .
        image: serhii-goodbye-html
        volumes:
            - .:/app
        environment:
            - TERM=xterm-256color
        tty: true
        stdin_open: true
